# This is a basic workflow to help you get started with Actions

name: update-room-url

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  schedule:
    - cron: '0 17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        node-version: [ 16.x ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          #cache: 'npm'

      - name: setup and install python packages
        run: |
          pip install -r requirements.txt

      - name: install nodejs dependences
        working-directory: ./nodejs
        run: |
          npm i yarn -g
          yarn

      - name: update bilibili
        working-directory: ./nodejs
        run: node bilibili-batch.js

      - name: update douyu
        working-directory: ./nodejs
        run: node douyu-batch.js

      - name: update huya
        working-directory: ./nodejs
        run: node huya-batch.js

      - name: merge m3u files
        working-directory: ./nodejs
        run: node all-m3u.js

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: m3u data
          path: |
            data

